# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subsample <- function(circle, size) {
    .Call(`_rayfocus_subsample`, circle, size)
}

subsample_rect <- function(rect, binsx, binsy) {
    .Call(`_rayfocus_subsample_rect`, rect, binsx, binsy)
}

gen_circle_psf <- function(radius) {
    .Call(`_rayfocus_gen_circle_psf`, radius)
}

is_inside <- function(sizehex, positionx, positiony, sinval, cosval) {
    .Call(`_rayfocus_is_inside`, sizehex, positionx, positiony, sinval, cosval)
}

gen_hex_psf <- function(radius, rotation) {
    .Call(`_rayfocus_gen_hex_psf`, radius, rotation)
}

psf <- function(image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel) {
    .Call(`_rayfocus_psf`, image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel)
}

