# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subsample <- function(circle, size) {
    .Call(`_rayimage_subsample`, circle, size)
}

rayinterp2 <- function(image, XI, YI) {
    .Call(`_rayimage_rayinterp2`, image, XI, YI)
}

resize_image <- function(image, mag) {
    .Call(`_rayimage_resize_image`, image, mag)
}

resize_image_xy <- function(image, magx, magy) {
    .Call(`_rayimage_resize_image_xy`, image, magx, magy)
}

generate_disk <- function(radius, dim) {
    .Call(`_rayimage_generate_disk`, radius, dim)
}

gen_ellipse <- function(intensity, width, height) {
    .Call(`_rayimage_gen_ellipse`, intensity, width, height)
}

subsample_rect <- function(rect, binsx, binsy) {
    .Call(`_rayimage_subsample_rect`, rect, binsx, binsy)
}

gen_circle_psf <- function(radius) {
    .Call(`_rayimage_gen_circle_psf`, radius)
}

is_inside <- function(sizehex, positionx, positiony, sinval, cosval) {
    .Call(`_rayimage_is_inside`, sizehex, positionx, positiony, sinval, cosval)
}

gen_hex_psf <- function(radius, rotation) {
    .Call(`_rayimage_gen_hex_psf`, radius, rotation)
}

psf <- function(image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel) {
    .Call(`_rayimage_psf`, image, blurmatrix, depthmap, depth, custombokeh, type, bokehintensity, bokehlimit, rotation, progbar, channel)
}

convolution_cpp <- function(image, kernel, progbar, channel, bloom_matrix) {
    .Call(`_rayimage_convolution_cpp`, image, kernel, progbar, channel, bloom_matrix)
}

